src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_time = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): static
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                'attr' => ['class' => 'form-control mt-2'],
                'label_attr' => ['class' => 'text-white']
            ])
            ->add('date_time',  null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2'],
                "widget" => "single_text"
            ])
            ->add('description', null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2']
            ])
            ->add('image', null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2']
            ])
            ->add('capacity', null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2']
            ])
            ->add('email', null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2']
            ])
            ->add('phone', null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2']
            ])
            ->add('address', null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2']
            ])
            ->add('type', ChoiceType::class, [
                'attr' => ['class' => 'form-control mt-1'],
                'choices'  => [
                    'Music' => "music",
                    'Sport' => "sport",
                    'Movie' => "movie",
                    'Theater' => "theater",
                    'Operette' => "operette",
                    'Fun' => "fun",
                ],

                'label_attr' => ['class' => 'text-white my-2']
            ])
            ->add('url', null, [
                'attr' => ['class' => 'form-control mt-1'],
                'label_attr' => ['class' => 'text-white my-2']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/')]
class EventController extends AbstractController
{
    #[Route('/event', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/filter/{type}', name: 'filter_events', methods: ['GET'])]
    public function filterEventsByType($type, EventRepository $eventRepository): Response
    {
        $events = $eventRepository->findBy(['type' => $type]);
        $template = match ($type) {
            'music' => 'event/music.html.twig',
            'sport' => 'event/sport.html.twig',
            'movie' => 'event/movie.html.twig',
            'theater' => 'event/theater.html.twig',
            'operette' => 'event/operette.html.twig',
            'fun' => 'event/fun.html.twig',
            default => 'event/index.html.twig',
        };
        return $this->render($template, [
            'events' => $events,
        ]);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger mt-2">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mt-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit event 🖊{% endblock %}

{% block body %}
<div class="container col-6 shadow_1 mt-5 pb-4 rounded">
    <h1 class="text-warning py-3">Edit Event 🖊</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-secondary mt-2" href="{{ path('app_event_index') }}">Back to list</a>

    {{ include('event/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/event/fun.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events 🎉{% endblock %}

{% block body %}

            <div class="container">
                <h1 class="text-light text-center fw-bold my-4">Event index 🎉</h1>
                <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">
                    {% for event in events %}

                    <div class="card m-3 shadow_1" style="width: 20rem;">
                        <img src="{{ event.image }}" class="card-img-top hover-zoom shadow" alt="..." style="height: 270px;" width="250px;">
                        <div class="card-body">
                          <h5 class="card-title">{{ event.name }}</h5>
                          <hr>
                          {# <p class="card-text"><span>Description:</span><br> {{ event.description }}</p> #}
                          <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳: H:i:s') : '' }}</p>
                          <p class="card-text"><span>Type:</span> {{ event.type }}</p>
                          <hr>
                          <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-success">Details</a>
                          <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
                          <a class="btn btn-secondary" href="{{ path('app_event_index') }}">Back to list</a>
                        </div>
                      </div>


                    {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                    {% endfor %}
                    
                </div>
                <a class="btn btn-primary mt-3 mx-1" href="{{ path('app_event_new') }}">Create new</a>
            </div>

{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events 🎉{% endblock %}

{% block body %}

            <div class="container">
                <h1 class="text-light text-center fw-bold my-4">Event index 🎉</h1>
                <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">
                    {% for event in events %}

                    <div class="card m-3 shadow_1" style="width: 20rem;">
                        <img src="{{ event.image }}" class="card-img-top hover-zoom shadow" alt="..." style="height: 270px;" width="250px;">
                        <div class="card-body">
                          <h5 class="card-title">{{ event.name }}</h5>
                          <hr>
                          {# <p class="card-text"><span>Description:</span><br> {{ event.description }}</p> #}
                          <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳: H:i:s') : '' }}</p>
                          <p class="card-text"><span>Type:</span> {{ event.type }}</p>
                          <hr>
                          <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-success">Details</a>
                          <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
                          {{ include('event/_delete_form.html.twig') }}
                        </div>
                      </div>


                    {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                    {% endfor %}
                    
                </div>
                <a class="btn btn-primary mt-3 mx-1" href="{{ path('app_event_new') }}">Create new</a>
            </div>

{% endblock %}

templates/event/movie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events 🎉{% endblock %}

{% block body %}

            <div class="container">
                <h1 class="text-light text-center fw-bold my-4">Event index 🎉</h1>
                <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">
                    {% for event in events %}

                    <div class="card m-3 shadow_1" style="width: 20rem;">
                        <img src="{{ event.image }}" class="card-img-top hover-zoom shadow" alt="..." style="height: 270px;" width="250px;">
                        <div class="card-body">
                          <h5 class="card-title">{{ event.name }}</h5>
                          <hr>
                          {# <p class="card-text"><span>Description:</span><br> {{ event.description }}</p> #}
                          <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳: H:i:s') : '' }}</p>
                          <p class="card-text"><span>Type:</span> {{ event.type }}</p>
                          <hr>
                          <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-success">Details</a>
                          <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
                          <a class="btn btn-secondary" href="{{ path('app_event_index') }}">Back to list</a>
                        </div>
                      </div>


                    {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                    {% endfor %}
                    
                </div>
                <a class="btn btn-primary mt-3 mx-1" href="{{ path('app_event_new') }}">Create new</a>
            </div>

{% endblock %}

templates/event/music.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events 🎉{% endblock %}

{% block body %}

            <div class="container">
                <h1 class="text-light text-center fw-bold my-4">Event index 🎉</h1>
                <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">
                    {% for event in events %}

                    <div class="card m-3 shadow_1" style="width: 20rem;">
                        <img src="{{ event.image }}" class="card-img-top hover-zoom shadow" alt="..." style="height: 270px;" width="250px;">
                        <div class="card-body">
                          <h5 class="card-title">{{ event.name }}</h5>
                          <hr>
                          {# <p class="card-text"><span>Description:</span><br> {{ event.description }}</p> #}
                          <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳: H:i:s') : '' }}</p>
                          <p class="card-text"><span>Type:</span> {{ event.type }}</p>
                          <hr>
                          <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-success">Details</a>
                          <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
                          <a class="btn btn-secondary" href="{{ path('app_event_index') }}">Back to list</a>
                        </div>
                      </div>


                    {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                    {% endfor %}
                    
                </div>
                <a class="btn btn-primary mt-3 mx-1" href="{{ path('app_event_new') }}">Create new</a>
            </div>

{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event 🎉{% endblock %}

{% block body %}
<div class="container col-6 rounded shadow_1">
    <h1 class="text-primary py-3">Create new Event 🎉</h1>

    {{ include('event/_form.html.twig') }}

    <a class="btn btn-secondary my-3" href="{{ path('app_event_index') }}">Back to list</a>
</div>
{% endblock %}

templates/event/operette.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events 🎉{% endblock %}

{% block body %}

            <div class="container">
                <h1 class="text-light text-center fw-bold my-4">Event index 🎉</h1>
                <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">
                    {% for event in events %}

                    <div class="card m-3 shadow_1" style="width: 20rem;">
                        <img src="{{ event.image }}" class="card-img-top hover-zoom shadow" alt="..." style="height: 270px;" width="250px;">
                        <div class="card-body">
                          <h5 class="card-title">{{ event.name }}</h5>
                          <hr>
                          {# <p class="card-text"><span>Description:</span><br> {{ event.description }}</p> #}
                          <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳: H:i:s') : '' }}</p>
                          <p class="card-text"><span>Type:</span> {{ event.type }}</p>
                          <hr>
                          <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-success">Details</a>
                          <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
                          <a class="btn btn-secondary" href="{{ path('app_event_index') }}">Back to list</a> 
                        </div>
                      </div> 

                    {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                    {% endfor %}
                    
                </div>
                <a class="btn btn-primary mt-3 mx-1" href="{{ path('app_event_new') }}">Create new</a>
            </div>

{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event 💫{% endblock %}

{% block body %}
    <h1 class="text-white text-center mb-4">Event details 💫</h1>
<div class="container d-flex justify-content-center">
    <div class="card col-5 shadow_1">
        <img src="{{ event.image }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ event.name }}</h5>
            <hr>
            <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳ H:i:s') : '' }}</p>
            <p class="card-text"><span>Description:</span><br> {{ event.description }}</p>
            <p class="card-text"><span>Type:</span> {{ event.type }}</p>
            <p class="card-text"><span>Capacity:</span> {{ event.capacity }}</p>
            <p class="card-text"><span>Address:</span> {{ event.address }}</p>
            <p class="card-text"><span>Phone:</span> {{ event.phone }}</p>
            <p class="card-text"><span>Email:</span> {{ event.email }}</p>
            <p class="card-text"><span>Web:</span> {{ event.url }}</p>
            <hr>
            <a class="btn btn-secondary" href="{{ path('app_event_index') }}">Back to list</a>

            <a class="btn btn-warning mx-1" href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>
        
            {{ include('event/_delete_form.html.twig') }}
    
        </div>
    </div>
</div>

{% endblock %}

templates/event/sport.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events 🎉{% endblock %}

{% block body %}

            <div class="container">
                <h1 class="text-light text-center fw-bold my-4">Event index 🎉</h1>
                <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">
                    {% for event in events %}

                    <div class="card m-3 shadow_1" style="width: 20rem;">
                        <img src="{{ event.image }}" class="card-img-top hover-zoom shadow" alt="..." style="height: 270px;" width="250px;">
                        <div class="card-body">
                          <h5 class="card-title">{{ event.name }}</h5>
                          <hr>
                          <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳: H:i:s') : '' }}</p>
                          <p class="card-text"><span>Type:</span> {{ event.type }}</p>
                          <hr>
                          <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-success">Details</a>
                          <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
                          <a class="btn btn-secondary" href="{{ path('app_event_index') }}">Back to list</a>
                        </div>
                      </div>


                    {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                    {% endfor %}
                    
                </div>
                <a class="btn btn-primary mt-3 mx-1" href="{{ path('app_event_new') }}">Create new</a>
            </div>

{% endblock %}

templates/event/theater.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events 🎉{% endblock %}

{% block body %}

            <div class="container">
                <h1 class="text-light text-center fw-bold my-4">Event index 🎉</h1>
                <div class="row row-cols-lg-4 row-cols-md-3 row-cols-sm-2 row-cols-xs-1">
                    {% for event in events %}

                    <div class="card m-3 shadow_1" style="width: 20rem;">
                        <img src="{{ event.image }}" class="card-img-top hover-zoom shadow" alt="..." style="height: 270px;" width="250px;">
                        <div class="card-body">
                          <h5 class="card-title">{{ event.name }}</h5>
                          <hr>
                          {# <p class="card-text"><span>Description:</span><br> {{ event.description }}</p> #}
                          <p class="card-text"><span>📅:</span> {{ event.dateTime ? event.dateTime|date('Y-m-d ⏳: H:i:s') : '' }}</p>
                          <p class="card-text"><span>Type:</span> {{ event.type }}</p>
                          <hr>
                          <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-success">Details</a>
                          <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-warning">Edit</a>
                          <a class="btn btn-secondary" href="{{ path('app_event_index') }}">Back to list</a>
                        </div>
                      </div>


                    {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                    {% endfor %}
                    
                </div>
                <a class="btn btn-primary mt-3 mx-1" href="{{ path('app_event_new') }}">Create new</a>
            </div>

{% endblock %}